/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multi_threading;

/**
 *
 * @author Ahmad Habib
 */
import javax.swing.JOptionPane;
public class kuis_matematika extends javax.swing.JFrame {

    /**
     * Creates new form kuis_matematika
     */
static int benar = 0;
static int flag = 0;

public void hitungskor(){
String soal1 = jawaban1.getText();
String soal2 = jawaban2.getText();
String soal3 = jawaban3.getText();
String soal4 = jawaban4.getText();

if(soal1.equals("623")==true){ // equals() sama aja kayak == 
benar +=1;
}
if(soal2.equals("504")==true){
benar +=1;
}
if(soal3.equals("4")==true){
benar +=1;
}
if(soal4.equals("199")==true){
benar +=1;
}
dispose();// dispose itu artinya akan menghapus tampilan/ jendela  , coba liat lagi yang materii file jar

}

public class Timer1 implements Runnable{ //
@Override
public void run(){
try{
Thread.sleep(60000);// ini 60.000 60 detik maksudnya dibuat tidur selama 1 menit , begitu dia bangun maka dia disuruh mengerjakan hitungskor();
hitungskor();// mirip hitung mundur gitu lah , hitung mundur setelah waktu habis maka intruksi dijalankan 
if(flag == 0){
JOptionPane.showMessageDialog(null,"waktu  habis, anda menjawab benar "+benar+"soal ");

}else{}

}catch(InterruptedException ie){
JOptionPane.showMessageDialog(null, ie);
}
}

}

public class Timer2 implements Runnable{
@Override
public void run(){
for(int i = 59; i>0;i --){
try{
Thread.sleep(1000);
jLabel6.setText("waktu anda tersisa "+i+" detik");
}
catch(InterruptedException ie){
JOptionPane.showMessageDialog(null, ie);
}
}
}
}

    public kuis_matematika() {
        initComponents(); // menjalankan fungsi kuis_matematika 
Thread a = new Thread(new Timer1()); // sekaligus menjalankan thread timer1 , jadi keduanya berkerja secara pararel 
Thread b = new Thread(new Timer2()); // thread timer1 dan timer2 bekerja secara secara bersamaan (secara pararel)
a.start();
b.start();
//thread yang berjalana program kuissmatetmatika nya , kemudian timer1 sebagai penanda waktu telah habis , kemudian timer2 sebagai fungsi hitung mundur
// jadi multi threading ini , kita membuat thread yang bekerja seacara bersamaan 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jawaban1 = new javax.swing.JTextField();
        jawaban2 = new javax.swing.JTextField();
        jawaban3 = new javax.swing.JTextField();
        jawaban4 = new javax.swing.JTextField();
        tombol_jawab = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("masukan jawaban yang benar selama 60 detik");

        jLabel2.setText("1. 212 + 411  = ");

        jLabel3.setText("2. 21 x 24       =");

        jLabel4.setText("3. 212 / 53     =");

        jLabel5.setText("4. 411 - 212   =");

        tombol_jawab.setText("jawab");
        tombol_jawab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_jawabActionPerformed(evt);
            }
        });

        jLabel6.setText("waktu anda tersisa 60 detik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jawaban4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jawaban3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jawaban2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jawaban1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tombol_jawab)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel6)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jawaban1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jawaban2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jawaban3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jawaban4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tombol_jawab)))
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_jawabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_jawabActionPerformed
        // TODO add your handling code here:
flag = 1;
hitungskor();
JOptionPane.showMessageDialog(null, "anda menjawab benar "+benar+" soal");//ingat selalu messagedialog(nul, isi) null isi null isi
    }//GEN-LAST:event_tombol_jawabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis_matematika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis_matematika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis_matematika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis_matematika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis_matematika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jawaban1;
    private javax.swing.JTextField jawaban2;
    private javax.swing.JTextField jawaban3;
    private javax.swing.JTextField jawaban4;
    private javax.swing.JToggleButton tombol_jawab;
    // End of variables declaration//GEN-END:variables
}
